[package]
name = "kfiles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_engine = { version = "2.6.0", features = ["form", "event"] }
opener =  { version = "0.6.1", features = ["reveal"] }

[lib]
name = "filebuffer"
path = "src/lib.rs"