[package]
name = "kfiles"
version = "0.2.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_engine = { version = "2.6.0", features = ["form", "event"] }
opener =  { version = "0.6.1", features = ["reveal"] }
confy = "0.5.1"
serde = { version = "1.0.183", features = ["derive"] }
directories = "5.0.1"
clean-path = "0.2.1"
